POST http://127.0.0.1:8000/api/accounts/login
Content-Type: application/json

{"username": "Skusam16", "password": "Ahoj12345"}


###

POST http://127.0.0.1:8000/api/accounts/register
Content-Type: application/json

{"username": "Skusam16", "password": "Ahoj12345", "email": "skusam16@skusam.com"}


###

GET http://127.0.0.1:8000/api/accounts/test_token
Content-Type: application/json
# HERE WE NEED TO RECIVE AS A HEADER LINE BELOW key: Authorization value: TOKEN 34klnasldaoid...(user token stored on client side) 
Authorization: Token f447aa6bb71925842c15d4ff70dd36f121126cbc

{}

###

POST http://127.0.0.1:8000/api/accounts/logout
Content-Type: application/json

{}

###

GET http://127.0.0.1:8000/api/accounts/user-profile/Skusam15
Content-Type: application/json
# HERE WE NEED TO RECIVE AS A HEADER LINE BELOW key: Authorization value: TOKEN 34klnasldaoid...(user token stored on client side) 
Authorization: Token 73055e0d17f051ee34d212280080d941e4854380

{}

###

GET http://127.0.0.1:8000/api/accounts/users/15
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/api/accounts/user-profile/Skusam13
Content-Type: application/json
# HERE WE NEED TO RECIVE AS A HEADER LINE BELOW key: Authorization value: TOKEN 34klnasldaoid...(user token stored on client side) 
Authorization: Token 47639153103302da869f26396cd22bef3588adfa

{}

###

GET http://127.0.0.1:8000/api/accounts/home/visible
Content-Type: application/json

{}

###
POST http://127.0.0.1:8000/api/accounts/skills
Content-Type: application/json
Authorization: Token d56d60f8c279487594e44aa0d8cfa622ac1acecc

{"name": "Java Frajer"}

###
POST http://127.0.0.1:8000/api/accounts/projects
Content-Type: application/json
Authorization: Token d56d60f8c279487594e44aa0d8cfa622ac1acecc

{"name": "Bomba", "link": "https://ahoj.sk"}