# Generated by Django 5.0.2 on 2024-05-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_about_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mainSkills',
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name1', models.CharField(blank=True, max_length=20, verbose_name='Skill1')),
                ('project_link1', models.URLField(blank=True, max_length=100, verbose_name='Skill link1')),
                ('project_name2', models.CharField(blank=True, max_length=20, verbose_name='Skill2')),
                ('project_link2', models.URLField(blank=True, max_length=100, verbose_name='Skill link')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name1', models.CharField(blank=True, max_length=20, verbose_name='Skill1')),
                ('skill_name2', models.CharField(blank=True, max_length=20, verbose_name='Skill2')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.userprofile')),
            ],
        ),
    ]
