# Generated by Django 5.0.2 on 2024-05-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_mainskills_projects_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_link1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_link2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_name1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_name2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_name1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_name2',
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
